# Create numpy array

In [1]:
import numpy as np
import warnings
warnings.filterwarnings('ignore')

In [2]:
array = np.array([1, 2, 3 ])
array

array([1, 2, 3])

In [3]:
array2 = np.array([[1, 2, 3], [4, 5, 6]])
array2

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
array3 = np.array([[[11, 12, 13], [14, 15, 16], [17, 18, 19]]])
array3

array([[[11, 12, 13],
        [14, 15, 16],
        [17, 18, 19]]])

# Numpy Assignment 1

Create a function that takes dimensions as tuples e.g.(3, 3) and a numeric value and returns a 
Numpy array of the given dimension filled with the given value e.g.: solve((3, 3), 5) will return 
[
 [5, 5, 5],
 [5, 5, 5],
 [5, 5, 5]
]

In [5]:
from itertools import starmap
import numpy as np

func = lambda a, b: np.full(a, b)

array5 = list(starmap(func, [((3, 3), 5)]))
array5

[array([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])]

Create a method that takes n Numpy arrays of same dimensions sums them and return the 
answer.

In [6]:
n = int(input("Enter the dimension in 1d space: "))
m = int(input("Enter the value you want to fill in array: "))

arraysum = np.full(
  shape=n,
  fill_value=m,
  dtype=np.int
)
print(arraysum)
print(np.sum(arraysum))

Enter the dimension in 1d space: 3
Enter the value you want to fill in array: 3
[3 3 3]
9


In [7]:
# 2nd method

import numpy
arrays = numpy.repeat(5, 10)
print(arrays)
print(numpy.sum(arrays))

[5 5 5 5 5 5 5 5 5 5]
50


Given a 2 D Array of N X M Dimension, Write a function that accepts this array as well as two 
numbers N and M. The method should return the top-left N X M sub matrix e.g:
 [
 [1, 2, 3],
 [4, 5, 6],
 [7, 8, 9],
 ]
top_left_sub_matrix (matrix, 2, 2) -> should return:
 [
 [1, 2]
 [4, 5]
 ]


In [66]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
def array(arr):
    return arr[:2:]
    
array(arr)

array([[1, 2, 3],
       [4, 5, 6]])

Given a 2 D Array of N X M Dimension, Write a function that accepts this array as well as two 
numbers N and M The method should return the bottom-right N X M sub matrix e.g.:
 [
 [1, 2, 3],
 [4, 5, 6],
 [7, 8, 9],
 ]
sub_matrix(matrix, 1, 1) -> should return : (Keep in mind these arrays are zero indexed)
 [
 [5, 6]
 [8, 9]
 ]

In [35]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
def array(arr):
    return arr[1:, 1:]
    
array(arr)

array([[5, 6],
       [8, 9]])

Given a 1 D Numpy Array. Write a function that accepts this array as parameters. The method 
should return a dictionary with 'mean' and 'std_dev' as key and array's mean and array's 
standard deviation as values:
 [1, 1, 1]

solution(arr) -> should return :
 {'mean': 1.0, 'std_dev': 0.0

In [32]:
array = np.array([1, 1, 1])

def arr(array):
    mean = array.mean()
    std = array.std()
    Dict = {"mean": mean, "std_dev": std}
    
    return Dict

arr(array)

{'mean': 1.0, 'std_dev': 0.0}

# Numpy Assignment 2

Create a 3x3 matrix array with values ranging from 2 to 10

In [10]:
array3d = np.arange(2,11).reshape(3, 3)
array3d

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

Create a numpy array having user input values and convert the integer type to the float type 
of the elements of the array. For instance:
Original array
[1, 2, 3, 4]
Array converted to a float type:
[ 1. 2. 3. 4.

In [33]:
my_array = []
a=int(input("Size of array:"))
for i in range(a):
    x=float(input("Element:"))
    my_array.append(x)

my_array2 = np.array(my_array)
print(my_array2)

Size of array:3
Element:1
Element:2
Element:3
[1. 2. 3.]


Write a Numpy program to append values to the end of an array. For instance:
Original array:
[10, 20, 30]
After append values to the end of the array:
[10 20 30 40 50 60 70 80 90

In [ ]:
x = [10, 20, 30]
print("Original array:")
print(x)
x = np.append(x, [[40, 50, 60], [70, 80, 90]])
print("After append values to the end of the array:")
print(x)

Create two numpy arrays and add the elements of both the arrays and store the result in 
sumArray.

In [ ]:
First_array = np.array([1, 2, 3])
Second_array = np.array([4, 5, 6])
sumArray = First_array + Second_array
print(sumArray)

Create a 3*3 array having values from 10-90(interval of 10) and store that in array1. Perform 
the following tasks:
a. Extract the 1st row from the array.
b. Extract the last element from the array

In [ ]:
array1 = np.arange(10, 100, 10).reshape(3, 3)
array1

In [ ]:
# Task a

array1[0]

In [ ]:
# Task b

array1[2][2]

### 